name: AnyHack CI

on: [push]

jobs:
  ubuntu-build:
    name: ${{matrix.buildname}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            buildname: 'ubuntu'
            triplet: x64-linux
            compiler: gcc_64
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build project
      uses: lukka/run-cmake@v2
      with:
        cmakeGenerator: 'Ninja'  
        cmakeBuildType: 'Release'
        buildWithCMakeArgs: '--target package'
        buildDirectory: "${{ github.workspace }}/build"
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: debpkg
        path: "${{ github.workspace }}/build/anyhack_*.deb"
