name: AnyHack CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: lukka/run-cmake@v0.10
      with:
        cmakeGenerator: 'Ninja'  
        cmakeBuildType: 'Release'
        buildWithCMakeArgs: 'package'
        buildDirectory: "${{ github.workspace }}/build"
